<?php

/**
 * @file
 * Un módulo de bloque que 
 */

function importar_recetas_block_info()
{
    $block['importar_recetas'] = array(
        'info' => t('Importar Recetas'),
        'cache' => DRUPAL_NO_CACHE,
    );
    $block['pagina_importar_recetas'] = array(
        'info' => t('Página Importar Recetas'),
        'cache' => DRUPAL_NO_CACHE,
    );	
	
	return $block;
}

function importar_recetas_block_view($val)
{
	if($val == 'importar_recetas'){
		$mc = 6;
		$link = '/recetas/';
		$titulo = '
			<div id="nuestras-recetas">
				<div class="nuestras-recetas-titulo">
					<h2>Nuestras <b>recetas</b></h2>
				</div>
				<div class="nuestras-recetas-desc">
				<p>Conozca las manos que preparan nuestros productos.</p>
				</div>
			</div>
		';
	}else if($val == 'pagina_importar_recetas'){
		$mc = 48;
		$link = 'javascript:masRecetas();';
		$titulo = '
			<p>Pruebe las recetas deliciosas y saludables, hechas con ingredientes naturales y frescos cortesía de www.comaorganico.com. </p>
		';		
	}
	$path = drupal_get_path('module', 'importar_recetas');

	$url_on = "http://comaorganico.com/category/recetas/feed/";
	$url_lo = $path . "/recetas.xml";
	$modificado_lo = 0;
	
	if(file_exists($url_lo)){
		$rss = simplexml_load_file($url_lo);
		$modificado_lo = strtotime($rss->channel->lastBuildDate);		
	}

	$h = get_headers($url_on, 1);
	$modificado_on = strtotime($h['Last-Modified']);
	
	if($modificado_on > $modificado_lo){
		$xml = file_get_contents($url_on);
		$fp = fopen($path . '/recetas.xml', "w+");
		fputs($fp, $xml);
		$rss = simplexml_load_file($url_lo);
	}
	
	$html = '
	
	<div class="nuestras_recetas_full">
		<div class="grid-24">
		'.$titulo.'
			<div class="recetas">';
	$cant = 1;
	foreach ($rss as $items) {   
		foreach($items->item as $item){ 
			$html .= '<div class="receta row_'.$cant.'">';
			
			$html .= '
			<a href="'.$item->link.'" target="_blank">
			<div class="receta_img" style="background-image: url('.$item->img.');"></div>
			</a>';
			
			$html .= '<div class="receta_info">
			<a class="receta_titulo" href="'.$item->link.'" target="_blank">'.substr($item->title, 0, 70).'</a>';
			
			$html .= '<p>';
			if($item->cookingtime!=''){
				$html .= $item->cookingtime . ' min';
			}
			if($item->serves!=''){
				$html .= ' | '.$item->serves . ' personas';
			}	
			$html .= '</p>';
			
			$html .= '<div class="icons_recetas">';
			foreach($item->categorias as $cs){ 
				foreach($cs->categoria as $c){
					switch($c['id']){
						case '330':
							$html .= '<div data-tooltip="'.$c.'"><img src="/'.$path.'/images/icon_1.png" ></div>';
						break;
						case '331':
							$html .= '<div data-tooltip="'.$c.'"><img src="/'.$path.'/images/icon_2.png" ></div>';
						break;
						case '332':
							$html .= '<div data-tooltip="'.$c.'"><img src="/'.$path.'/images/icon_3.png" ></div>';
						break;
						case '333':
							$html .= '<div data-tooltip="'.$c.'"><img src="/'.$path.'/images/icon_4.png" ></div>';
						break;
						case '334':
							$html .= '<div data-tooltip="'.$c.'"><img src="/'.$path.'/images/icon_5.png" ></div>';
						break;																
					}
				}
			}
			$html .= '</div>'; $html .= '</div>';
			$html .= '<a class="receta_flecha" href="'.$item->link.'" target="_blank">&nbsp;</a>';
			
			
			$item->categorias . ' <br />' .
			
			'
			<br /><br /><br /><br />
			';
			
			$html .= '</div>';
			if($cant==$mc){ break; }
			$cant = $cant + 1;
		} 
	}
	$html .= '
	</div>
	
	<div class="more-link">
		<a href="'.$link.'">Ver Todas</a>
	</div>
	
		</div>
			</div>';
	
	
	$block['content'] = $html;
	
	return $block;
}
